name: Build RecipeBox Android App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: |
          mkdir -p dist
          cp index.html style.css script.js manifest.json sw.js dist/

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses >/dev/null

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode Keystore
        if: ${{ env.KEYSTORE_FILE != '' }}
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: |
          echo "$KEYSTORE_FILE" | base64 --decode > android/keystore.jks
          echo "KEYSTORE_EXISTS=true" >> $GITHUB_ENV
        
      - name: Build Signed Android APK
        working-directory: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          if [ "$KEYSTORE_EXISTS" = "true" ]; then
            echo "Building signed release APK..."
            ./gradlew assembleRelease \
              -Pandroid.injected.signing.store.file=keystore.jks \
              -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
              -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
              -Pandroid.injected.signing.key.password="$KEY_PASSWORD" \
              --no-daemon --stacktrace
          else
            echo "No keystore found, building debug APK..."
            ./gradlew assembleDebug --no-daemon --stacktrace
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RecipeBox.apk
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: RecipeBox v${{ github.run_number }}
          files: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/debug/app-debug.apk
          body: |
            🍳 **RecipeBox v${{ github.run_number }} - Your Cooking Companion**
            
            **Features:**
            - 📖 Comprehensive Recipe Collection (50+ recipes)
            - 🧮 Salt Concentration Calculator  
            - ⚖️ Container Weight Database
            - 📱 Mobile-Optimized Interface
            - 🔄 Ingredient Scaling (1-4 servings)
            - 🎯 One-tap recipe access
            
            **Installation:**
            1. Download the APK file below
            2. Enable "Install from Unknown Sources" in Android settings  
            3. Install the APK
            
            **Version Info:**
            - Version Code: ${{ github.run_number }}
            - Build: ${{ github.sha }}
            
            **APK Downloads:**
            - `app-release.apk`: Signed release version (recommended)
            - `app-debug.apk`: Debug version (fallback)
            
            **Installation:**
            - Use the signed release APK for consistent updates
            - No more manual uninstall required!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}