name: Build RecipeBox Android App with Advanced Signing

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: |
          mkdir -p dist
          cp index.html style.css script.js manifest.json sw.js dist/

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses >/dev/null

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 署名付きAPK生成とアイコン置換システム
      - name: Build Signed APK with Custom Icon
        if: secrets.KEYSTORE_FILE
        working-directory: android
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          NEW_VERSION_CODE: ${{ github.run_number }}
        run: |
          chmod +x gradlew
          
          # キーストア復元
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > recipebox-release-key.p12
          
          # 署名付きリリースAPK生成
          ./gradlew assembleRelease --no-daemon --stacktrace
          
          # RecipeBoxカスタムアイコン作成
          mkdir -p $RUNNER_TEMP/icons
          
          # カスタムアイコンをPNG形式で作成（レシピブックデザイン）
          cat > $RUNNER_TEMP/create_icon.py << 'EOF'
          from PIL import Image, ImageDraw, ImageFont
          import os
          
          def create_recipe_icon(size, output_path):
              # 背景色：温かみのあるオレンジ
              bg_color = "#FF8C00"  # DarkOrange
              
              # 画像作成
              img = Image.new('RGB', (size, size), bg_color)
              draw = ImageDraw.Draw(img)
              
              # 本のアウトライン
              margin = size * 0.15
              book_left = margin
              book_right = size - margin
              book_top = margin * 0.8
              book_bottom = size - margin * 0.8
              
              # 本の背景（白）
              draw.rectangle([book_left, book_top, book_right, book_bottom], 
                           fill="#FFFFFF", outline="#8B4513", width=max(2, size//64))
              
              # ページライン
              line_spacing = (book_bottom - book_top) * 0.15
              for i in range(3):
                  y = book_top + line_spacing * (i + 2)
                  draw.line([book_left + margin*0.3, y, book_right - margin*0.3, y], 
                           fill="#CCCCCC", width=max(1, size//128))
              
              # 調理器具アイコン（フォーク＆ナイフ風）
              center_x, center_y = size // 2, size // 2
              utensil_size = size * 0.15
              
              # フォーク（左）
              fork_x = center_x - utensil_size * 0.7
              draw.line([fork_x, center_y - utensil_size, fork_x, center_y + utensil_size], 
                       fill="#8B4513", width=max(3, size//32))
              draw.line([fork_x - utensil_size*0.3, center_y - utensil_size*0.8, 
                        fork_x + utensil_size*0.3, center_y - utensil_size*0.8], 
                       fill="#8B4513", width=max(2, size//48))
              
              # ナイフ（右）
              knife_x = center_x + utensil_size * 0.7
              draw.line([knife_x, center_y - utensil_size, knife_x, center_y + utensil_size], 
                       fill="#8B4513", width=max(3, size//32))
              
              # 角丸処理のための再描画
              mask = Image.new('L', (size, size), 0)
              mask_draw = ImageDraw.Draw(mask)
              corner_radius = size // 8
              mask_draw.rounded_rectangle([0, 0, size, size], corner_radius, fill=255)
              
              # 角丸適用
              result = Image.new('RGBA', (size, size), (0, 0, 0, 0))
              result.paste(img, (0, 0))
              result.putalpha(mask)
              
              result.save(output_path, 'PNG')
              print(f"Created icon: {output_path} ({size}x{size})")
          
          # 各サイズのアイコン生成
          sizes = [48, 72, 96, 144, 192, 384, 512, 1024]
          for size in sizes:
              create_recipe_icon(size, f"/tmp/recipe_icon_{size}.png")
          EOF
          
          # Python環境確認とアイコン生成
          if command -v python3 >/dev/null 2>&1; then
              python3 -m pip install --user Pillow >/dev/null 2>&1 || true
              python3 $RUNNER_TEMP/create_icon.py || echo "Icon generation failed, using default"
          else
              echo "Python not available, using default icons"
          fi
          
          # APKアイコン置換（無圧縮再パッケージ方式）
          original_apk="app/build/outputs/apk/release/app-release.apk"
          
          if [ -f "$original_apk" ] && [ -f "/tmp/recipe_icon_192.png" ]; then
              echo "🎨 Replacing APK icons with custom RecipeBox icon..."
              
              # APK展開
              mkdir -p $RUNNER_TEMP/apk_extract
              cd $RUNNER_TEMP/apk_extract
              unzip -q "$GITHUB_WORKSPACE/android/$original_apk"
              
              # アイコン置換
              for dir in res/mipmap-*; do
                  if [ -d "$dir" ]; then
                      # 基本アイコン
                      cp /tmp/recipe_icon_192.png "$dir/ic_launcher.png" 2>/dev/null || true
                      cp /tmp/recipe_icon_192.png "$dir/ic_launcher_round.png" 2>/dev/null || true
                      cp /tmp/recipe_icon_192.png "$dir/ic_launcher_foreground.png" 2>/dev/null || true
                      echo "Updated icons in $dir"
                  fi
              done
              
              # 署名削除
              rm -rf META-INF
              
              # 無圧縮再パッケージ（重要：CRC保持）
              zip -r -0 $RUNNER_TEMP/modified.apk . >/dev/null
              
              # APK構造診断
              if command -v aapt2 >/dev/null 2>&1; then
                  echo "🔍 APK Structure Diagnostic:"
                  if aapt2 dump badging $RUNNER_TEMP/modified.apk > /tmp/aapt_output.txt 2>&1; then
                      echo "✅ APK structure valid"
                      grep "application-label:" /tmp/aapt_output.txt || true
                      grep "application-icon-" /tmp/aapt_output.txt || true
                  else
                      echo "❌ APK structure problems detected"
                      head -5 /tmp/aapt_output.txt || true
                  fi
              fi
              
              # Zipalign + 署名
              if command -v zipalign >/dev/null 2>&1 && command -v apksigner >/dev/null 2>&1; then
                  zipalign -p -f 4 $RUNNER_TEMP/modified.apk $RUNNER_TEMP/aligned.apk
                  
                  # 自動エイリアス検出
                  KEY_ALIAS_DETECTED=$(keytool -list -keystore recipebox-release-key.p12 -storetype PKCS12 -storepass "$KEYSTORE_PASSWORD" 2>/dev/null | grep "Alias name:" | head -1 | cut -d: -f2 | xargs)
                  FINAL_ALIAS="${KEY_ALIAS:-$KEY_ALIAS_DETECTED}"
                  
                  echo "🔐 Signing APK with alias: $FINAL_ALIAS"
                  apksigner sign --ks recipebox-release-key.p12 \
                    --ks-pass pass:"$KEYSTORE_PASSWORD" \
                    --key-pass pass:"$KEYSTORE_PASSWORD" \
                    --ks-key-alias "$FINAL_ALIAS" \
                    --v1-signing-enabled true \
                    --v2-signing-enabled true \
                    --v3-signing-enabled true \
                    --out $RUNNER_TEMP/final.apk $RUNNER_TEMP/aligned.apk
                  
                  # 署名検証
                  if apksigner verify $RUNNER_TEMP/final.apk; then
                      echo "✅ APK signature verification successful"
                      cp $RUNNER_TEMP/final.apk "$GITHUB_WORKSPACE/android/app/build/outputs/apk/release/app-release.apk"
                  else
                      echo "❌ APK signature verification failed, using original"
                  fi
              else
                  echo "⚠️ zipalign/apksigner not available, using unaligned APK"
                  cp $RUNNER_TEMP/modified.apk "$GITHUB_WORKSPACE/android/app/build/outputs/apk/release/app-release.apk"
              fi
              
              cd "$GITHUB_WORKSPACE/android"
          else
              echo "⚠️ Original APK or custom icon not found, proceeding with original APK"
          fi

      # Debug APK（署名なし）
      - name: Build Debug APK
        if: ${{ !secrets.KEYSTORE_FILE }}
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RecipeBox-v${{ github.run_number }}.apk
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: RecipeBox v${{ github.run_number }}
          files: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/debug/app-debug.apk
          body: |
            🍳 **RecipeBox v${{ github.run_number }} - Your Cooking Companion**
            
            **New in this version:**
            - 🎨 Custom RecipeBox icon (recipe book design)
            - 🔧 Enhanced APK update compatibility
            - 📱 Seamless app updates without uninstall/reinstall
            - 🔐 Advanced APK signing (v1+v2+v3 signatures)
            
            **Features:**
            - 📖 Comprehensive Recipe Collection (50+ recipes)
            - 🧮 Salt Concentration Calculator  
            - ⚖️ Container Weight Database
            - 📱 Mobile-Optimized Interface
            - 🔄 Ingredient Scaling (1-4 servings)
            - 🎯 One-tap recipe access
            
            **Installation:**
            1. Download the APK file below
            2. Enable "Install from Unknown Sources" in Android settings  
            3. Install the APK
            4. **Updates:** Future versions will install over this one seamlessly
            
            **Download Options:**
            - `app-release.apk`: Signed production build (recommended)
            - `app-debug.apk`: Debug build (fallback)
            
            **Version Info:**
            - Version Code: ${{ github.run_number }}
            - Build: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}